schema_version = "1.0.0"

id = "pop_agent"
version = "1.3.0"
name = "JhonYan"
tagline = "Blender Agent powered by OpenAI and DeepSeek"
maintainer = "POPTools"
type = "add-on"

# link to documentation, support, source files, etc
website = ""

# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["User Interface", "Development", "Text Editor"]

blender_version_min = "5.1.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
blender_version_max = "5.1.999"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = ["SPDX:GPL-2.0-or-later"]

# For each permission it is important to also specify the reason why it is required.
# Keep this a single short sentence without a period (.) at the end.
# For longer explanations use the documentation or detail page.
# Options are: files, network, clipboard, camera, microphone
#
[permissions]
network = "Call LLM providers and Tavily web search when requested by the user"
# files = "Import/export FBX from/to disk"
# clipboard = "Copy and paste bone transforms"
