from .blender_query import QUERY_SCENE, LIST_ADDONS, VIEWPORT_SCREENSHOT
from .blender_api_docs import BLENDER_API_SEARCH
from .blender_select import SELECT_OBJECTS, SET_ACTIVE
from .blender_nodes import (
    SEARCH_NODE_TYPES,
    INSPECT_MATERIAL_NODES,
    VALIDATE_MATERIAL_NODES,
    CONNECT_PBR_TEXTURES,
    ADD_MATERIAL_NODE,
    CONNECT_MATERIAL_NODES,
    SET_MATERIAL_NODE_INPUT,
    INSPECT_GEOMETRY_NODES,
    VALIDATE_GEOMETRY_NODES,
    ENSURE_BASIC_GEOMETRY_NODES,
    ADD_GEOMETRY_NODE,
    CONNECT_GEOMETRY_NODES,
    SET_GEOMETRY_NODE_INPUT,
)
from .blender_mesh import HEALTH_CHECK
from .blender_file import SAVE_FILE
from .blender_edit import UNDO, REDO
from .blender_transform import TRANSFORM_SET, TRANSFORM_APPLY, TRANSFORM_SET_ORIGIN
from .blender_object import (
    DELETE_OBJECTS,
    DUPLICATE_OBJECT,
    PARENT_OBJECTS,
    ORGANIZE_COLLECTION,
)
from .agent_meta import LIST_SKILLS
from .agent_interact import ASK_HUMAN
from .dev_skills import RUN_PYTHON
from ..agent_core import skill_registry

_BUILTIN_SKILLS = [
    QUERY_SCENE,
    LIST_ADDONS,
    VIEWPORT_SCREENSHOT,
    BLENDER_API_SEARCH,
    SELECT_OBJECTS,
    SET_ACTIVE,
    SEARCH_NODE_TYPES,
    INSPECT_MATERIAL_NODES,
    VALIDATE_MATERIAL_NODES,
    CONNECT_PBR_TEXTURES,
    ADD_MATERIAL_NODE,
    CONNECT_MATERIAL_NODES,
    SET_MATERIAL_NODE_INPUT,
    INSPECT_GEOMETRY_NODES,
    VALIDATE_GEOMETRY_NODES,
    ENSURE_BASIC_GEOMETRY_NODES,
    ADD_GEOMETRY_NODE,
    CONNECT_GEOMETRY_NODES,
    SET_GEOMETRY_NODE_INPUT,
    HEALTH_CHECK,
    SAVE_FILE,
    UNDO,
    REDO,
    TRANSFORM_SET,
    TRANSFORM_APPLY,
    TRANSFORM_SET_ORIGIN,
    DELETE_OBJECTS,
    DUPLICATE_OBJECT,
    PARENT_OBJECTS,
    ORGANIZE_COLLECTION,
    LIST_SKILLS,
    ASK_HUMAN,
    RUN_PYTHON,
]


def register():
    for skill in _BUILTIN_SKILLS:
        skill_registry.register_skill(skill)


def unregister():
    skill_registry.unregister_namespace("builtin")
